[default_line_fitting]
O1_6300A_m = "O1_6300A+S3_6312A"
O2_7319A_m = "O2_7319A+O2_7320A+O2_7330A+O2_7331A"

map_band_vsigma.O1_6300A = 140
map_band_vsigma.S3_6312A = 140
map_band_vsigma.H1_6563A = 300
map_band_vsigma.N2_6583A = 300
map_band_vsigma.N2_6548A = 300

[only_n2_line_fitting]
H1_6563A_b = 'H1_6563A+H1_6563A_k-1+N2_6583A+N2_6548A'
H1_6563A_k-1_sigma ='expr:>1.5*H1_6563A_sigma'
N2_6548A_amp = 'expr:N2_6583A_amp/2.94'
N2_6548A_kinem = 'N2_6583A'

[Halpha_plus_nitrogen_line_fitting]
H1_6563A_b = 'H1_6563A+H1_6563A_k-1+N2_6583A+N2_6548A'
H1_6563A_k-1_sigma ='expr:>1.4*H1_6563A_sigma'
N2_6548A_amp = 'expr:N2_6583A_amp/2.94'
N2_6548A_kinem = 'H1_6563A'
N2_6583A_kinem = 'H1_6563A'
