[default_line_fitting]

H1_18756A_b = 'H1_18756A+He1_18691A'
H2-4-3-O2_31588A_m = 'H2-4-3-O2_31588A+H2-3-2-O3_31638A'
H2-4-3-O2_31588A_b = 'H2-4-3-O2_31588A+H2-3-2-O3_31638A'
H1_16412A_b = 'H1_16412A+Fe2_16440A'

rejected_lines = ['Fe2_12791A', 'H2-4-3-O2_31588A', 'Si6_19650A']
